
# /////////////////////////////////////////////////////////////////////
# This file is a part of the BSTools package
# written by Przemyslaw Kiciak
# /////////////////////////////////////////////////////////////////////
# (C) Copyright by Przemyslaw Kiciak, 2005
# this package is distributed under the terms of the
# Lesser GNU Public License, see the file COPYING.LIB
# /////////////////////////////////////////////////////////////////////

default:
	(cd cpict;make)
	(cd Polish;make)
	(cd English;make)

clean:
	(cd cpict;make clean)
	(cd Polish;make clean)
	(cd English;make clean)

mrproper:
	(cd cpict;make mrproper)
	(cd Polish;make mrproper)
	(cd English;make mrproper)

