
# /////////////////////////////////////////////////////////////////////
# This file is a part of the BSTools package
# written by Przemyslaw Kiciak
# /////////////////////////////////////////////////////////////////////
# (C) Copyright by Przemyslaw Kiciak, 2005, 2015
# this package is distributed under the terms of the
# Lesser GNU Public License, see the file COPYING.LIB
# /////////////////////////////////////////////////////////////////////

HOME = /home/przemek
SRCDIR = .
INCDIR = ../../include
LIBDIR = ../../lib

include ../../options.mak

OBJECTS = mbs01fd.o \
  mbs0001f.o mbs0002f.o mbs0003f.o mbs0004f.o mbs0005f.o mbs0006f.o \
  mbs0007f.o mbs0008f.o mbs0009f.o mbs0010f.o mbs0011f.o mbs0012f.o \
  mbs0013f.o mbs0014f.o mbs0015f.o mbs0016f.o mbs0017f.o mbs0018f.o \
  mbs0019f.o mbs0020f.o mbs0021f.o mbs0022f.o mbs0023f.o mbs0024f.o \
  mbs0025f.o mbs0026f.o mbs0027f.o mbs0028f.o mbs0029f.o mbs0030f.o \
  mbs0031f.o mbs0032f.o mbs0033f.o mbs0034f.o mbs0035f.o mbs0036f.o \
  mbs0037f.o mbs0038f.o mbs0039f.o mbs0040f.o mbs0041f.o mbs0042f.o \
  mbs0043f.o mbs0044f.o mbs0045f.o mbs0046f.o mbs0047f.o mbs0048f.o \
  mbs0049f.o mbs0050f.o mbs0051f.o mbs0052f.o mbs0053f.o mbs0054f.o \
  mbs0055f.o mbs0056f.o mbs0057f.o mbs0058f.o mbs0059f.o mbs0060f.o \
  mbs0061f.o mbs0062f.o mbs0063f.o mbs0064f.o mbs0065f.o mbs0066f.o \
  mbs0067f.o mbs0068f.o mbs0069f.o mbs0070f.o mbs0071f.o mbs0072f.o \
  mbs0073f.o mbs0074f.o mbs0075f.o mbs0076f.o mbs0077f.o mbs0078f.o \
  mbs0079f.o mbs0080f.o mbs0081f.o mbs0082f.o mbs0083f.o mbs0084f.o \
  mbs0085f.o \
  mbs0001d.o mbs0002d.o mbs0003d.o mbs0004d.o mbs0005d.o mbs0006d.o \
  mbs0007d.o mbs0008d.o mbs0009d.o mbs0010d.o mbs0011d.o mbs0012d.o \
  mbs0013d.o mbs0014d.o mbs0015d.o mbs0016d.o mbs0017d.o mbs0018d.o \
  mbs0019d.o mbs0020d.o mbs0021d.o mbs0022d.o mbs0023d.o mbs0024d.o \
  mbs0025d.o mbs0026d.o mbs0027d.o mbs0028d.o mbs0029d.o mbs0030d.o \
  mbs0031d.o mbs0032d.o mbs0033d.o mbs0034d.o mbs0035d.o mbs0036d.o \
  mbs0037d.o mbs0038d.o mbs0039d.o mbs0040d.o mbs0041d.o mbs0042d.o \
  mbs0043d.o mbs0044d.o mbs0045d.o mbs0046d.o mbs0047d.o mbs0048d.o \
  mbs0049d.o mbs0050d.o mbs0051d.o mbs0052d.o mbs0053d.o mbs0054d.o \
  mbs0055d.o mbs0056d.o mbs0057d.o mbs0058d.o mbs0059d.o mbs0060d.o \
  mbs0061d.o mbs0062d.o mbs0063d.o mbs0064d.o mbs0065d.o mbs0066d.o \
  mbs0067d.o mbs0068d.o mbs0069d.o mbs0070d.o mbs0071d.o mbs0072d.o \
  mbs0073d.o mbs0074d.o mbs0075d.o mbs0076d.o mbs0077d.o mbs0078d.o \
  mbs0079d.o mbs0080d.o mbs0081d.o mbs0082d.o mbs0083d.o mbs0084d.o \
  mbs0085d.o \
  mbs01f.o mbs02f.o mbs03f.o mbs04f.o mbs05f.o mbs06f.o mbs07f.o mbs08f.o \
  mbs09f.o mbs10f.o mbs11f.o mbs13f.o mbs14f.o mbs16f.o \
  mbs17f.o mbs18f.o mbs19f.o mbs20f.o mbs21f.o mbs22f.o mbs23f.o mbs24f.o \
  mbs25f.o mbs26f.o mbs27f.o mbs28f.o mbs29f.o mbs30f.o mbs31f.o \
  mbs36f.o mbs37f.o mbs38f.o mbs41f.o \
  mbs42f.o mbs43f.o mbs45f.o mbs46f.o mbs47f.o mbs48f.o \
  mbs51f.o mbs52f.o mbs53f.o mbs54f.o mbs55f.o mbs56f.o mbs57f.o \
  mbs58f.o mbs60f.o mbs61f.o mbs62f.o \
  mbs01d.o mbs02d.o mbs03d.o mbs04d.o mbs05d.o mbs06d.o mbs07d.o mbs08d.o \
  mbs09d.o mbs10d.o mbs11d.o mbs13d.o mbs14d.o mbs16d.o \
  mbs17d.o mbs18d.o mbs19d.o mbs20d.o mbs21d.o mbs22d.o mbs23d.o mbs24d.o \
  mbs25d.o mbs26d.o mbs27d.o mbs28d.o mbs29d.o mbs30d.o mbs31d.o \
  mbs36d.o mbs37d.o mbs38d.o mbs41d.o \
  mbs42d.o mbs43d.o mbs45d.o mbs46d.o mbs47d.o mbs48d.o \
  mbs51d.o mbs52d.o mbs53d.o mbs54d.o mbs55d.o mbs56d.o mbs57d.o \
  mbs58d.o mbs60d.o mbs61d.o mbs62d.o

TARGET = $(LIBDIR)/libmultibs.a

default: $(TARGET)

$(TARGET): $(OBJECTS)
	$(AR) $(ARFLAGS) $(TARGET) $(OBJECTS)

.c.o: $< $(INCDIR)/msgpool.h $(INCDIR)/pkvaria.h $(INCDIR)/pknum.h \
  $(INCDIR)/pkgeom.h $(INCDIR)/pkgeomf.h $(INCDIR)/pkgeomd.h \
  $(INCDIR)/multibs.h $(INCDIR)/multibsf.h $(INCDIR)/multibsd.h
	$(CC) $(CFLAGS) -I$(INCDIR) -c $< -o $*.o

clean:
	rm -f $(OBJECTS)

mrproper:
	rm -f $(OBJECTS)
	rm -f $(TARGET)
