
# /////////////////////////////////////////////////////////////////////
# This file is a part of the BSTools package
# written by Przemyslaw Kiciak
# /////////////////////////////////////////////////////////////////////
# (C) Copyright by Przemyslaw Kiciak, 2005, 2012
# this package is distributed under the terms of the
# Lesser GNU Public License, see the file COPYING.LIB
# /////////////////////////////////////////////////////////////////////

default:
	(cd simplest; make)
	(cd template; make)
	(cd pokrzyw; make)
	(cd pognij; make)
	(cd pomnij; make)
	(cd polep; make)
	(cd polepG1; make)
	(cd polepG2; make)
	(cd policz; make)
	(cd pozwalaj; make)
	(cd poruszaj; make)
	(cd simplest.gl; make)
	(cd tiffsh; make)
	(cd ifs; make)

clean:
	(cd simplest; make clean)
	(cd template; make clean)
	(cd pokrzyw; make clean)
	(cd pognij; make clean)
	(cd pomnij; make clean)
	(cd polep; make clean)
	(cd polepG1; make clean)
	(cd polepG2; make clean)
	(cd policz; make clean)
	(cd pozwalaj; make clean)
	(cd poruszaj; make clean)
	(cd simplest.gl; make clean)
	(cd tiffsh; make clean)
	(cd ifs; make clean)

mrproper:
	(cd simplest; make mrproper)
	(cd template; make mrproper)
	(cd pokrzyw; make mrproper)
	(cd pognij; make mrproper)
	(cd pomnij; make mrproper)
	(cd polep; make mrproper)
	(cd polepG1; make mrproper)
	(cd polepG2; make mrproper)
	(cd policz; make mrproper)
	(cd pozwalaj; make mrproper)
	(cd poruszaj; make mrproper)
	(cd simplest.gl; make mrproper)
	(cd tiffsh; make mrproper)
	(cd ifs; make mrproper)

