
# /////////////////////////////////////////////////////////////////////
# This file is a part of the BSTools package
# written by Przemyslaw Kiciak
# /////////////////////////////////////////////////////////////////////
# (C) Copyright by Przemyslaw Kiciak, 2010, 2014
# this package is distributed under the terms of the
# Lesser GNU Public License, see the file COPYING.LIB
# /////////////////////////////////////////////////////////////////////

HOME = /home/przemek
SRCDIR = .
INCDIR = ../../include
LIBDIR = ../../lib

include ../../options.mak

OBJECTS = $(SRCDIR)/bsmesh00.o $(SRCDIR)/bsmesh01.o $(SRCDIR)/bsmesh02.o \
  $(SRCDIR)/bsmesh03d.o $(SRCDIR)/bsmesh04.o  $(SRCDIR)/bsmesh05d.o \
  $(SRCDIR)/bsmesh06d.o $(SRCDIR)/bsmesh07d.o $(SRCDIR)/bsmesh08.o  \
  $(SRCDIR)/bsmesh09d.o $(SRCDIR)/bsmesh10.o  $(SRCDIR)/bsmesh11d.o \
  $(SRCDIR)/bsmesh12.o  $(SRCDIR)/bsmesh13d.o $(SRCDIR)/bsmesh14.o  \
  $(SRCDIR)/bsmesh15d.o $(SRCDIR)/bsmesh16.o  $(SRCDIR)/bsmesh17d.o \
  $(SRCDIR)/bsmesh18.o  $(SRCDIR)/bsmesh19.o  $(SRCDIR)/bsmesh20.o  \
  $(SRCDIR)/bsmesh21.o  $(SRCDIR)/bsmesh22.o  $(SRCDIR)/bsmesh23.o  \
  $(SRCDIR)/bsmesh24.o  $(SRCDIR)/bsmesh25d.o $(SRCDIR)/bsmesh26d.o \
  $(SRCDIR)/bsmesh27d.o $(SRCDIR)/bsmesh28d.o $(SRCDIR)/bsmesh29.o  \
  $(SRCDIR)/bsmesh30.o  $(SRCDIR)/bsmesh31d.o $(SRCDIR)/bsmesh32d.o \
  $(SRCDIR)/bsmesh33d.o $(SRCDIR)/bsmesh34d.o $(SRCDIR)/bsmesh35d.o \
  $(SRCDIR)/bsmesh36d.o $(SRCDIR)/bsmesh37d.o $(SRCDIR)/bsmesh38d.o

TARGET = $(LIBDIR)/libbsmesh.a

default: $(TARGET)

$(TARGET): $(OBJECTS)
	$(AR) $(ARFLAGS) $(TARGET) $(OBJECTS)

.c.o:
	$(CC) -c $(CFLAGS) -I$(INCDIR) $< -o $*.o

$(SRCDIR)/bsmesh00.o: $(SRCDIR)/bsmesh00.c $(INCDIR)/bsmesh.h $(SRCDIR)/bsmprivate.h

$(SRCDIR)/bsmesh01.o: $(SRCDIR)/bsmesh01.c $(INCDIR)/bsmesh.h $(SRCDIR)/bsmprivate.h

$(SRCDIR)/bsmesh02.o: $(SRCDIR)/bsmesh02.c $(INCDIR)/bsmesh.h $(SRCDIR)/bsmprivate.h

$(SRCDIR)/bsmesh03d.o: $(SRCDIR)/bsmesh03d.c $(INCDIR)/bsmesh.h $(SRCDIR)/bsmprivate.h

$(SRCDIR)/bsmesh04.o: $(SRCDIR)/bsmesh04.c $(INCDIR)/bsmesh.h $(SRCDIR)/bsmprivate.h

$(SRCDIR)/bsmesh05d.o: $(SRCDIR)/bsmesh05d.c $(INCDIR)/bsmesh.h $(SRCDIR)/bsmprivate.h

$(SRCDIR)/bsmesh06d.o: $(SRCDIR)/bsmesh06d.c $(INCDIR)/bsmesh.h $(SRCDIR)/bsmprivate.h

$(SRCDIR)/bsmesh07d.o: $(SRCDIR)/bsmesh07d.c $(INCDIR)/bsmesh.h $(SRCDIR)/bsmprivate.h

$(SRCDIR)/bsmesh08.o: $(SRCDIR)/bsmesh08.c $(INCDIR)/bsmesh.h $(SRCDIR)/bsmprivate.h

$(SRCDIR)/bsmesh09d.o: $(SRCDIR)/bsmesh09d.c $(INCDIR)/bsmesh.h $(SRCDIR)/bsmprivate.h

$(SRCDIR)/bsmesh10.o: $(SRCDIR)/bsmesh10.c $(INCDIR)/bsmesh.h $(SRCDIR)/bsmprivate.h

$(SRCDIR)/bsmesh11d.o: $(SRCDIR)/bsmesh11d.c $(INCDIR)/bsmesh.h $(SRCDIR)/bsmprivate.h

$(SRCDIR)/bsmesh12.o: $(SRCDIR)/bsmesh12.c $(INCDIR)/bsmesh.h $(SRCDIR)/bsmprivate.h

$(SRCDIR)/bsmesh13d.o: $(SRCDIR)/bsmesh13d.c $(INCDIR)/bsmesh.h $(SRCDIR)/bsmprivate.h

$(SRCDIR)/bsmesh14.o: $(SRCDIR)/bsmesh14.c $(INCDIR)/bsmesh.h $(SRCDIR)/bsmprivate.h

$(SRCDIR)/bsmesh15d.o: $(SRCDIR)/bsmesh15d.c $(INCDIR)/bsmesh.h $(SRCDIR)/bsmprivate.h

$(SRCDIR)/bsmesh16.o: $(SRCDIR)/bsmesh16.c $(INCDIR)/bsmesh.h $(SRCDIR)/bsmprivate.h

$(SRCDIR)/bsmesh17d.o: $(SRCDIR)/bsmesh17d.c $(INCDIR)/bsmesh.h $(SRCDIR)/bsmprivate.h

$(SRCDIR)/bsmesh18.o: $(SRCDIR)/bsmesh18.c $(INCDIR)/bsmesh.h $(SRCDIR)/bsmprivate.h

$(SRCDIR)/bsmesh19.o: $(SRCDIR)/bsmesh19.c $(INCDIR)/bsmesh.h $(SRCDIR)/bsmprivate.h

$(SRCDIR)/bsmesh20.o: $(SRCDIR)/bsmesh20.c $(INCDIR)/bsmesh.h $(SRCDIR)/bsmprivate.h

$(SRCDIR)/bsmesh21.o: $(SRCDIR)/bsmesh21.c $(INCDIR)/bsmesh.h $(SRCDIR)/bsmprivate.h

$(SRCDIR)/bsmesh22.o: $(SRCDIR)/bsmesh22.c $(INCDIR)/bsmesh.h $(SRCDIR)/bsmprivate.h

$(SRCDIR)/bsmesh23.o: $(SRCDIR)/bsmesh23.c $(INCDIR)/bsmesh.h $(SRCDIR)/bsmprivate.h

$(SRCDIR)/bsmesh24.o: $(SRCDIR)/bsmesh24.c $(INCDIR)/bsmesh.h $(SRCDIR)/bsmprivate.h

$(SRCDIR)/bsmesh25d.o: $(SRCDIR)/bsmesh25d.c $(INCDIR)/bsmesh.h $(SRCDIR)/bsmprivate.h

$(SRCDIR)/bsmesh26d.o: $(SRCDIR)/bsmesh26d.c $(INCDIR)/bsmesh.h $(SRCDIR)/bsmprivate.h

$(SRCDIR)/bsmesh27d.o: $(SRCDIR)/bsmesh27d.c $(INCDIR)/bsmesh.h $(SRCDIR)/bsmprivate.h

$(SRCDIR)/bsmesh28d.o: $(SRCDIR)/bsmesh28d.c $(INCDIR)/bsmesh.h $(SRCDIR)/bsmprivate.h

$(SRCDIR)/bsmesh29.o: $(SRCDIR)/bsmesh29.c $(INCDIR)/bsmesh.h $(SRCDIR)/bsmprivate.h

$(SRCDIR)/bsmesh30.o: $(SRCDIR)/bsmesh30.c $(INCDIR)/bsmesh.h $(SRCDIR)/bsmprivate.h

$(SRCDIR)/bsmesh31d.o: $(SRCDIR)/bsmesh31d.c $(INCDIR)/bsmesh.h $(SRCDIR)/bsmprivate.h

$(SRCDIR)/bsmesh32d.o: $(SRCDIR)/bsmesh32d.c $(INCDIR)/bsmesh.h $(SRCDIR)/bsmprivate.h

$(SRCDIR)/bsmesh33d.o: $(SRCDIR)/bsmesh33d.c $(INCDIR)/bsmesh.h $(SRCDIR)/bsmprivate.h

$(SRCDIR)/bsmesh34d.o: $(SRCDIR)/bsmesh34d.c $(INCDIR)/bsmesh.h $(SRCDIR)/bsmprivate.h

$(SRCDIR)/bsmesh35d.o: $(SRCDIR)/bsmesh35d.c $(INCDIR)/bsmesh.h $(SRCDIR)/bsmprivate.h

$(SRCDIR)/bsmesh36d.o: $(SRCDIR)/bsmesh36d.c $(INCDIR)/bsmesh.h $(SRCDIR)/bsmprivate.h

$(SRCDIR)/bsmesh37d.o: $(SRCDIR)/bsmesh37d.c $(INCDIR)/bsmesh.h $(SRCDIR)/bsmprivate.h

$(SRCDIR)/bsmesh38d.o: $(SRCDIR)/bsmesh38d.c $(INCDIR)/bsmesh.h $(SRCDIR)/bsmprivate.h

clean:
	rm -f $(OBJECTS)

mrproper:
	rm -f $(OBJECTS)
	rm -f $(TARGET)

