
# /////////////////////////////////////////////////////////////////////
# This file is a part of the BSTools package
# written by Przemyslaw Kiciak
# /////////////////////////////////////////////////////////////////////
# (C) Copyright by Przemyslaw Kiciak, 2005, 2015
# this package is distributed under the terms of the
# Lesser GNU Public License, see the file COPYING.LIB
# /////////////////////////////////////////////////////////////////////

HOME = /home/przemek
SRCDIR = .
INCDIR = ../include
LIBDIR = ../lib

default:
	(cd pkvaria;$(MAKE))
	(cd pknum;$(MAKE))
	(cd pkgeom;$(MAKE))
	(cd camera;$(MAKE))
	(cd multibs;$(MAKE))
	(cd bsmesh;$(MAKE))
	(cd g1blending;$(MAKE))
	(cd g2blending;$(MAKE))
	(cd psout;$(MAKE))
	(cd raybez;$(MAKE))
	(cd pkrender;$(MAKE))
	(cd eghole;$(MAKE))
	(cd xgedit;$(MAKE))
	(cd bsfile;$(MAKE))
	(cd mengerc;$(MAKE))
	(cd projects;$(MAKE))

clean:
	(cd pkvaria;$(MAKE) clean)
	(cd pknum;$(MAKE) clean)
	(cd pkgeom;$(MAKE) clean)
	(cd camera;$(MAKE) clean)
	(cd multibs;$(MAKE) clean)
	(cd bsmesh;$(MAKE) clean)
	(cd g1blending;$(MAKE) clean)
	(cd g2blending;$(MAKE) clean)
	(cd psout;$(MAKE) clean)
	(cd raybez;$(MAKE) clean)
	(cd pkrender;$(MAKE) clean)
	(cd eghole;$(MAKE) clean)
	(cd xgedit;$(MAKE) clean)
	(cd bsfile;$(MAKE) clean)
	(cd mengerc;$(MAKE) clean)
	(cd projects;$(MAKE) clean)

mrproper:
	(cd pkvaria;$(MAKE) mrproper)
	(cd pknum;$(MAKE) mrproper)
	(cd pkgeom;$(MAKE) mrproper)
	(cd camera;$(MAKE) mrproper)
	(cd multibs;$(MAKE) mrproper)
	(cd bsmesh;$(MAKE) mrproper)
	(cd g1blending;$(MAKE) mrproper)
	(cd g2blending;$(MAKE) mrproper)
	(cd psout;$(MAKE) mrproper)
	(cd raybez;$(MAKE) mrproper)
	(cd pkrender;$(MAKE) mrproper)
	(cd eghole;$(MAKE) mrproper)
	(cd xgedit;$(MAKE) mrproper)
	(cd bsfile;$(MAKE) mrproper)
	(cd mengerc;$(MAKE) mrproper)
	(cd projects;$(MAKE) mrproper)
